### PR TITLE
Added link comparisons

### PR DESCRIPTION
**Pull request by kaiser-chris**
Hi @DragonKnightOfBreeze,

as soon as we have squashed all bugs this can be merged.

Regards,

Chris

### CODE REVIEW

**Comment by kaiser-chris** [comment]
Ohh I noticed you already did this.

**Comment by DragonKnightOfBreeze** [comment]
I will merge it now

**Comment by DragonKnightOfBreeze** [comment]
image

What's this? links with same name and different i/o scopes?

**Comment by DragonKnightOfBreeze** [comment]
image

Is the left right and checked? I will keep the right temporarily.

**Review by DragonKnightOfBreeze — APPROVED** [review]

**Comment by kaiser-chris** [comment]
> image
> 
> What's this? links with same name and different i/o scopes?

This is used like this in base game:
image

Since law and law_type are different scopes and enactment_chance_for_law needs law_type.

**Comment by kaiser-chris** [comment]
> image
> 
> Is the left right and checked? I will keep the right temporarily.

Hmm I have not changed this one. Seems like this is from your changes I hadn't pulled.

**Comment by DragonKnightOfBreeze** [comment]
yeah

**Pull request merged**
